# Generated by Django 5.2.8 on 2025-11-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название модели')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('specifications', models.JSONField(default=dict, verbose_name='Характеристики')),
                ('description', models.TextField(verbose_name='Описание')),
                ('features', models.TextField(blank=True, verbose_name='Особенности')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показать в избранном')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Видеокамера',
                'verbose_name_plural': 'Видеокамеры',
                'ordering': ['-release_year'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='RecordingFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название формата')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('format_type', models.CharField(choices=[('analog', 'Аналоговый'), ('digital', 'Цифровой'), ('optical', 'Оптический диск'), ('flash', 'Флеш-память'), ('hdd', 'Встроенный HDD')], max_length=20, verbose_name='Тип формата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Формат записи',
                'verbose_name_plural': 'Форматы записи',
            },
        ),
        migrations.CreateModel(
            name='CameraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cameras/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cameras.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Изображение камеры',
                'verbose_name_plural': 'Изображения камер',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('document_type', models.CharField(choices=[('manual', 'Инструкция'), ('specs', 'Технические характеристики'), ('brochure', 'Брошюра'), ('service', 'Сервисное руководство')], max_length=50, verbose_name='Тип документа')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cameras.camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='camera',
            name='recording_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.recordingformat', verbose_name='Формат записи'),
        ),
    ]
